services:
  newsnow:
    build: .
    ports:
      - '33654:4444'
    volumes:
      - newsnow_data:/usr/app/.data
    env_file:
      - .env.server
    environment:
      - HOST=0.0.0.0
      - PORT=4444
      - NODE_ENV=production

volumes:
  newsnow_data:
    name: newsnow_data
